pdal:
  image: pdal/pdal:latest
  links:
    - database:database
  volumes:
    - /mnt/sources3d:/data
    - $PWD/pipeline:/pipeline

database:
  image: build.datapunt.amsterdam.nl:5000/atlas/pointcloud:latest
  ports:
    - "5432:5432"
  volumes:
    - /mnt/data3d/data:/var/lib/postgresql/data

