version: "2.1"

services:
  database:
    image: build.datapunt.amsterdam.nl:5000/atlas/pointcloud:latest
    ports:
      - "5432:5432"
    volumes:
      - /mnt/data3d/data:/var/lib/postgresql/data

  pdal:
    image: pdal/pdal:latest
    links:
      - database:database
    volumes:
      - /mnt/sources3d:/data
      - $PWD/pipeline:/pipeline

  3dfier:
    build: 3dfier
    links:
      - database:database
    volumes:
      - $PWD/viewer/output/Build/Cesium:/work/cesium
      - $PWD/3dfier/output:/output
    command: "cp /tiles/3dfier-tiles/conf/fragmentShader0.glsl /output/ && p /tiles/3dfier-tiles/conf/vertexShader0.glsl /output/"

  cesium:
    build: viewer
    volumes:
      - $PWD/viewer/output:/output
    command: "cp -R /viewer/cesium/Build /output/"

  x3d-service-ahn3:
    build: demo
    volumes:
      - $PWD/demo/app:/services/x3d_services/js
    links:
      - database:database
    ports:
      - "8081:8081"
    command: [forever, amsterdam_ahn3_service.js]

  x3d-service-adam:
    build: demo
    volumes:
      - $PWD/demo/app:/services/x3d_services/js
    links:
      - database:database
    ports:
      - "8080:8080"
    command: [forever, amsterdam_service.js]

  x3d-viewer:
    build: demo
    ports:
      - "80:80"
    volumes:
      - $PWD/3dfier/output:/var/www/html/output
      - $PWD/viewer/output/Build/Cesium:/var/www/html/cesium
    command: ["nginx", "-g", "daemon off;"]
